package com.lattice.latticeuser.entity;

import java.io.Serializable;
import java.util.Date;

public class Permission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.permissionID
     *
     * @mbggenerated
     */
    private Integer permissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.permissionName
     *
     * @mbggenerated
     */
    private String permissionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.roleID
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.permissionID
     *
     * @return the value of tb_permission.permissionID
     *
     * @mbggenerated
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.permissionID
     *
     * @param permissionid the value for tb_permission.permissionID
     *
     * @mbggenerated
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.permissionName
     *
     * @return the value of tb_permission.permissionName
     *
     * @mbggenerated
     */
    public String getPermissionname() {
        return permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.permissionName
     *
     * @param permissionname the value for tb_permission.permissionName
     *
     * @mbggenerated
     */
    public void setPermissionname(String permissionname) {
        this.permissionname = permissionname == null ? null : permissionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.status
     *
     * @return the value of tb_permission.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.status
     *
     * @param status the value for tb_permission.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.created
     *
     * @return the value of tb_permission.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.created
     *
     * @param created the value for tb_permission.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.updated
     *
     * @return the value of tb_permission.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.updated
     *
     * @param updated the value for tb_permission.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.roleID
     *
     * @return the value of tb_permission.roleID
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.roleID
     *
     * @param roleid the value for tb_permission.roleID
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}